version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./vite-svelte:/vite-svelte # コンテナ側の命名は次と合わせる [Dockerfile > WORKDIR] [.devcontainer/devcontainer.json > workspaceFolder]
      - node_modules:/vite-svelte/node_modules # named volumesで永続化
    command: sh -c "npm install && npm run build && while sleep 1000; do :; done" # 最後のコマンドはRemote Conteinersで起動時にコンテナが終了してしまわないようにしている
    ports:
      - 3000:3000
      - 24678:24678 # Vite + Docker環境で無限リロードしてしまうときの対処法(https://qiita.com/kiyoshiro/items/9dcba9af830f7ca51323)

volumes:
  node_modules: # named volumesで永続化
